### PR TITLE
[Remapping] 

### PR DESCRIPTION
**Pull request by Zarqu0n**
add change map topic when changing mode.
fix publish_map_once parameter. publish_maap_once disabled when mapping mode.

### CODE REVIEW

**Comment by Zarqu0n** [comment]
@oguzhankose @renbago can you review this.

**Comment by oguzhankose** [comment]
@Renbago i think this seems ok?

**Comment by Renbago** [comment]
reviewed its fine @Zarqu0n @oguzhankose

**Comment by Zarqu0n** [comment]
Okey im merging

**Pull request merged**
